apiVersion: v1
kind: Service
metadata:
  name: {{ include "database-chart.fullname" . }}
spec:
  selector:
    app: {{ include "database-chart.fullname" . }}
  ports:
    - port: 5432
  type: ClusterIP
