apiVersion: v1
kind: Service
metadata:
  name: {{ include "data-loader-chart.fullname" . }}
spec:
  selector:
    app: {{ include "data-loader-chart.fullname" . }}
  ports:
    - port: 5000
  type: ClusterIP
